### ISSUE TITLE
Login Error and Connection Error

### ISSUE THREAD

**Issue by Jacobean0** [instabot-py/instabot.py#1581]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [ x] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [ ] 3.x

## Description of your issue

```
I donno what is wrong with that but i have 'login and connection error' problem. i searched and tried some ways but still not working. 
if someone has any idea pls let me know thank u

08.09.2018_11:41 Login error! Connection error!
08.09.2018_11:41 Removing already liked medias..
08.09.2018_11:41 Trying to unfollow #1: 
08.09.2018_11:41 Removing already liked medias..
08.09.2018_11:41 Removing already liked medias..
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by xthedevistatorx** [comment]
Having the same error

**Comment by LopesX** [comment]
Instagram, banned us... do you have change the password and it work again...

**Comment by LopesX** [comment]
I think every time what fake_useragent change the browser we are banned

I receive a email:
"A new device was used to sign in to your Instagram account.
Windows - Opera - "City", "State", "Country"
September 11 at 12:41 PM (PDT)
If it was you, you can ignore this email. If not, change your password to protect your account.
You know more about keeping your account secure."

**Comment by nimrodazoulai** [comment]
Hi! What worked for me was changing the user agent in headers from self.user_agent (which meant it would be generated using fake_agent) to my actual user_agent. 
This way you are less likely to hit the unusual login attempt which causes your issue.
Let me know if that helped!

**Comment by Jacobean0** [comment]
> Worked to me too...
> I changed my line 166 or 169 of **instabot.py**:
> 
> * ```
>       self.user_agent = check_and_insert_user_agent(self, str(fake_ua.random))
>   ```
> 
> to
> 
> * ```
>      self.user_agent = ("PASTE YOUR USER_AGENT HERE")
>   ```
> 
> Search on GOOGLE: what is my user agent
> 
> Copy and Paste and Done

Thank You @LopesX its worked for me too but after ı faced with traceback problem and i fixed with "https://github.com/instabot-py/instabot.py/issues/1540#issuecomment-416862815" thank you to everyone

**Comment by xthedevistatorx** [comment]
Still not working. Updated line 166. Also used #1540 fix and it still is not working. Get "Except on Get_media!" error

**Comment by yxmphotography** [comment]
> Hi! What worked for me was changing the user agent in headers from self.user_agent (which meant it would be generated using fake_agent) to my actual user_agent.
> This way you are less likely to hit the unusual login attempt which causes your issue.
> Let me know if that helped!

My knowledge with this isn't that great. Can you explain the steps on how to fix this issue? I've been having this problem for the last 3 days.

**Comment by nimrodazoulai** [comment]
Hey @yxmphotography ,
1. go to the instabot directory
2. click on "src"
3. click on "instabot.py"
4. use cmnd+f / cntrl + f to find: **self.user_agent**
5. in the row of **self.user_agent** delete **check_and_insert_user_agent(self, str(fake_ua.random))**
6. go to google, search "what is my user agent" and copy the response.
7. paste it with parenthesis => **self.user_agent = ("PASTE YOUR USER_AGENT HERE")** 
8. save and try to run

**Comment by yxmphotography** [comment]
@nimrodazoulai  thanks for the quick reply. I managed to replace the info save and try to run it. It is still unsuccessful. Do you have any other suggestions? Or am I just blocked and I have to wait a certain period of time??

**Comment by nimrodazoulai** [comment]
@yxmphotography Are you receiving an error or still it fails to connect?

**Comment by knokkelmanns** [comment]
@nimrodazoulai i replaced user_agent with my own and i still have a problem
Login error! Connection error!
Removing already liked medias..

**Comment by nimrodazoulai** [comment]
@knokkelmanns I can send you a script that will mimic the login process and will deliver you as output the "challenge" url. (This is where the login process goes sideways)
What you'll need to do after is:
1. copy the challenge url
2. send the code to your mail
3. put the code in the challenge screen and hit the ok button
4. then your account will be whitelisted and you could reuse the bot.

**Comment by yxmphotography** [comment]
I'm still recieving the failure to connect

**Comment by yxmphotography** [comment]
> @knokkelmanns I can send you a script that will mimic the login process and will deliver you as output the "challenge" url. (This is where the login process goes sideways)
> What you'll need to do after is:
> 
> 1. copy the challenge url
> 2. send the code to your mail
> 3. put the code in the challenge screen and hit the ok button
> 4. then your account will be whitelisted and you could reuse the bot.

Will this fix my problem as well? If so, where would I find the login process to challenge the URL. or however, this process works. All details would be greatly appreciated 

Thank You

**Comment by TutOsirisOm** [comment]
@nimrodazoulai can you send me that script? I'm working an overall fix for everyone. I also have encountered this issue.

**Comment by knokkelmanns** [comment]
@nimrodazoulai send me please your script

**Comment by nimrodazoulai** [comment]
@knokkelmanns @TutOsirisOm , will attach the code here.
A few key points:
1. use this script to get the challenge url! not to perform login, I haven't had time to implement the email parser to complete the process automatically. Therefore you'll need to do the challenge yourself manually - the challenge url will send you to the mail address you signed up with.
Then submit the relevant code for the challenge and after you login successfully try to login again with the bot.
2. change the headers to fit your own.
3. insert your pass / username and run on terminal
4. sorry but It's not the prettiest code.

hope this helps.
let me know
[instalogin.py.zip](https://github.com/instabot-py/instabot.py/files/2380703/instalogin.py.zip)

**Comment by TutOsirisOm** [comment]
@nimrodazoulai Well, I can't say for sure if it works because the issue resolved itself on its own when I went to go check just now. If the issue occurs again with any of my accounts I will update here.

**Comment by knokkelmanns** [comment]
@nimrodazoulai thanks for your script, but today the bot has earned again without problems. if there are problems again I will use your decision

**Comment by kesha-antonov** [comment]
> @knokkelmanns @TutOsirisOm , will attach the code here.
> A few key points:
> 
> 1. use this script to get the challenge url! not to perform login, I haven't had time to implement the email parser to complete the process automatically. Therefore you'll need to do the challenge yourself manually - the challenge url will send you to the mail address you signed up with.
>    Then submit the relevant code for the challenge and after you login successfully try to login again with the bot.
> 2. change the headers to fit your own.
> 3. insert your pass / username and run on terminal
> 4. sorry but It's not the prettiest code.
> 
> hope this helps.
> let me know
> [instalogin.py.zip](https://github.com/instabot-py/instabot.py/files/2380703/instalogin.py.zip)

Did not work for me. I've submitted challenge code. Started bot. Same error

**Comment by nimrodazoulai** [comment]
@kesha-antonov did you change the user agent to fit your actual user agent? like in the answer mentioned above by @LopesX

**Comment by kesha-antonov** [comment]
> @kesha-antonov did you change the user agent to fit your actual user agent? like in the answer mentioned above by @LopesX

Yes. Tried that

**Comment by yxmphotography** [comment]
> @knokkelmanns @TutOsirisOm , will attach the code here.
> A few key points:
> 
> 1. use this script to get the challenge url! not to perform login, I haven't had time to implement the email parser to complete the process automatically. Therefore you'll need to do the challenge yourself manually - the challenge url will send you to the mail address you signed up with.
>    Then submit the relevant code for the challenge and after you login successfully try to login again with the bot.
> 2. change the headers to fit your own.
> 3. insert your pass / username and run on terminal
> 4. sorry but It's not the prettiest code.
> 
> hope this helps.
> let me know
> [instalogin.py.zip](https://github.com/instabot-py/instabot.py/files/2380703/instalogin.py.zip)

Can you explain how I would put this together? i replaced the information you provided to my information into the instalogin.py. but when I try to runn cmd it just opens and closes quickly

**Comment by nimrodazoulai** [comment]
@yxmphotography the instalogin should produce the challenge url, a url directing to the specific . challenge to whitelist your suspicious login attempt.
after you add your credentials / change headers to the .py file, running it on terminal should print it.
Can you please share your terminal output after you run it? 
Thanks

**Comment by nativecodeabuser** [comment]
@nimrodazoulai I'm very sorry for a dumb question but... when I invoke your code I get 12 alphanumerical characters (not url) and:
{"authenticated": false, "user":true, "status": "ok"}
Of course I filled it with proper credentials and headers to match those of my browser and instabot.py. What am I doing wrong?
I'm trying to combat the very same problem in the first place: "Login error! Connection error!"

**Comment by LopesX** [comment]
@nativecodeabuser Please open a new issue to your question... @Jacobean0 if works fine, please close the issue...

@nativecodeabuser For me instabot working fine now... download original files and fix some erros searching in issues.

**Comment by kawauti** [comment]
> Hey @yxmphotography ,
> 
> 1. go to the instabot directory
> 2. click on "src"
> 3. click on "instabot.py"
> 4. use cmnd+f / cntrl + f to find: **self.user_agent**
> 5. in the row of **self.user_agent** delete **check_and_insert_user_agent(self, str(fake_ua.random))**
> 6. go to google, search "what is my user agent" and copy the response.
> 7. paste it with parenthesis => **self.user_agent = ("PASTE YOUR USER_AGENT HERE")**
> 8. save and try to run

I got this error:   File "E:\_INSTA\src\instalogin.py", line 71
    print s.get("https://i.instagram.com/api/v1/users/1741863655/info/",headers=hdr).text
          ^
SyntaxError: invalid syntax

**Comment by jaspertz** [comment]
Easy. 

Just change your password and resketch the self-user agent. You're good to go 100%.
