### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

### ISSUE THREAD

**Issue by ar8001** [instabot-py/instabot.py#1642]
any idea whats wrong?

pi@raspberrypi:~/instagrambot/instabot.py $ sudo python followbot.py 
Traceback (most recent call last):
  File "followbot.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/pi/instagrambot/instabot.py/src/instabot.py", line 165, in __init__
    fake_ua = UserAgent()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by ryanbrewster124** [comment]
i just got the same, it was working fine two days ago

**Comment by humanautomatic** [comment]
the same, could be a breakdown

**Comment by emgugs** [comment]
Getting same.

**Comment by ar8001** [comment]
ok .. so its a instagram problem i  hope

**Comment by emgugs** [comment]
> ok .. so its a instagram problem i hope

Getting this error only on raspberry pi. On windows bot working fine with same account

**Comment by Giando** [comment]
same on Linux

**Comment by ryanbrewster124** [comment]
> [https://github.com/hellysmile/fake-useragent/issues/53](url)
> I tried this method. Now bot started working on python 2.7

strange that link leads me to nothing

**Comment by brain-wash** [comment]
I found a solution. If you use python3 to run the script it works just fine (at least for me). But you have to reinstall requests, fake_useragent etc. again with pip3.

**Comment by emgugs** [comment]
https://github.com/aancw/Belati/issues/29#issuecomment-383228159

> > [https://github.com/hellysmile/fake-useragent/issues/53](url)
> > I tried this method. Now bot started working on python 2.7
> 
> strange that link leads me to nothing

https://github.com/aancw/Belati/issues/29#issuecomment-383228159

**Comment by emgugs** [comment]
https://github.com/aancw/Belati/issues/29#issuecomment-383228159

**Comment by emgugs** [comment]
> I found a solution. If you use python3 to run the script it works just fine (at least for me). But you have to reinstall requests, fake_useragent etc. again with pip3.

Yes reinstalling works too;.

**Comment by humanautomatic** [comment]
UPDATE: SOLUTION FOUND!
after trying solutions from @emgugs and @brain-wash I reinstalled all the requirements and fake_useragent, then it shows at least login instead of crash directly, however it was not possible to login and with this error

Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "/Users/-/Documents/instabot.py-master 8/src/instabot.py", line 234, in init
self.login()
File "/Users/-/Documents/instabot.py-master 8/src/instabot.py", line 303, in login
self.user_id = ui.get_user_id_by_login(self.user_login)
File "/Users/-/Documents/instabot.py-master 8/src/userinfo.py", line 42, in get_user_id_by_login
json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

I fixed this by this method https://github.com/instabot-py/instabot.py/issues/1509#issuecomment-414965794 and now everything works on Python3

**Comment by ryanbrewster124** [comment]
still not working after reinstalling everything.

Narayans-iMac:instabot.py-master narayanbrewer$ python3 example.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/narayanbrewer/Desktop/instabot.py-master/src/instabot.py", line 165, in __init__
    fake_ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
Narayans-iMac:instabot.py-master narayanbrewer$

**Comment by budstankz** [comment]
anyone know how to fix this yet?

**Comment by budstankz** [comment]
how do I run the bot in python3 AND pip3?

**Comment by Daleee** [comment]
same issue here as @ryanbrewster124

**Comment by ryanbrewster124** [comment]
> pip install -r requirements.txt

i tried this and I get :

Narayans-iMac:instabot.py-master narayanbrewer$ pip install -r requirements.txt
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.19.1)
Requirement already satisfied: fake-useragent in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.1.10)
Requirement already satisfied: idna<2.8,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (2.7)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (2018.8.24)..

Anyone found a fix yet?

**Comment by som-m** [comment]
mine resolved with `pip install fake-useragent --upgrade`

**Comment by jirkajirka** [comment]
> mine resolved with `pip install fake-useragent --upgrade`

after this I got "Login error! Connection error!"

anyone knows how to fix it?

**Comment by ryanbrewster124** [comment]
> > mine resolved with `pip install fake-useragent --upgrade`
> 
> after this I got "Login error! Connection error!"
> 
> anyone knows how to fix it?

i fixed this issue once before with turning off two factor authentication, it's quite a common problem.
you can google it also as there are quite a few workarounds, good luck

**Comment by Daleee** [comment]
> mine resolved with `pip install fake-useragent --upgrade`

Massive stuff around. but i was using python 3.7. i uninstalled it and ran through the setup with 2.7. then ran the above upgrade and installed python3 again and now it works?

i dont understand but it's working lol

**Comment by shubhamkothari2808** [comment]
> mine resolved with `pip install fake-useragent --upgrade`

@som-m Can you please explain what and how exactly do I proceed? Not a coder/programmer, so I've no idea how to go ahead.

**Comment by monanabanana** [comment]
> mine resolved with `pip install fake-useragent --upgrade`

i tried this and get this:

`/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts/pip4console.py" && exit
python/scripts/pip4console.py" && exit   <
Input pip commands, ie: pip install {module}
-->pip install fake-useragent --upgrade
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/bin/pip", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(_requires_), Environment()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==9.0.3
-->`

Anyone can help me? Please??

**Comment by ar8001** [comment]
pip install fake-useragent --upgrade   

works for me too ... many thanks !!!!

**Comment by pierrechn** [comment]
Having the same issue, can 1 of you all provide a step by step on how to run the 'pip install fake-useragent --upgrade' fix ? 

I've uninstalled Python 3, installed python 2.7 and still getting the same issue.

**Comment by monanabanana** [comment]
I've deleted everything, restarted and reinstalled everything.
Then i put: **pip install fake-useragent --upgrade** and done succesfully, but get error when i run the bot:

`/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/projects/instabot.py-master/main.py" && exit
ts/instabot.py-master/main.py" && exit   <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/projects/instabot.py-master/main.py", line 49, in <module>
    unfollow_whitelist=[])
  File "/storage/emulated/0/qpython/projects/instabot.py-master/src/instabot.py", line 165, in _init_
    fake_ua = UserAgent()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/fake.py", line 69, in _init_
    self.load()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
1|F8331:/ $`

**Comment by shubhamkothari2808** [comment]
> Having the same issue, can 1 of you all provide a step by step on how to run the 'pip install fake-useragent --upgrade' fix ?
> 
> I've uninstalled Python 3, installed python 2.7 and still getting the same issue.

@pierrechn Open CMD on your pc and type "pip install fake-useragent --upgrade" and press enter. It'll show that an update is available along with a code to update the same. Use that code and things will update automatically. Reboot your system, just to be sure. Then use the instabot. It should work.

**Comment by shubhamkothari2808** [comment]
> > > Having the same issue, can 1 of you all provide a step by step on how to run the 'pip install fake-useragent --upgrade' fix ?
> > > I've uninstalled Python 3, installed python 2.7 and still getting the same issue.
> > 
> > 
> > @pierrechn Open CMD on your pc and type "pip install fake-useragent --upgrade" and press enter. It'll show that an update is available along with a code to update the same. Use that code and things will update automatically. Reboot your system, just to be sure. Then use the instabot. It should work.
> 
> thanks Shub, it's back up and running now! Appreciate the speedy response!

Great :) You're welcome :)

**Comment by wrigzzy** [comment]
when i try python i get this:

iMac:instabot.py-master williamwrig$ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/williamwrig/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/williamwrig/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/williamwrig/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests

when i try python3 i get this:

iMac:instabot.py-master williamwrig$ python3 example.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/williamwrig/Desktop/instabot.py-master/src/instabot.py", line 165, in __init__
    fake_ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
iMac:instabot.py-master williamwrig$

ive tried installing everything but i dont know what to do.

**Comment by monanabanana** [comment]
> I've deleted everything, restarted and reinstalled everything.
> Then i put: **pip install fake-useragent --upgrade** and done succesfully, but get error when i run the bot:
> 
> `/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/projects/instabot.py-master/main.py" && exit ts/instabot.py-master/main.py" && exit < Traceback (most recent call last): File "/storage/emulated/0/qpython/projects/instabot.py-master/main.py", line 49, in <module> unfollow_whitelist=[]) File "/storage/emulated/0/qpython/projects/instabot.py-master/src/instabot.py", line 165, in _init_ fake_ua = UserAgent() File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/fake.py", line 69, in _init_ self.load() File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/fake.py", line 78, in load verify_ssl=self.verify_ssl, File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl) File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 245, in update write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl)) File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 189, in load verify_ssl=verify_ssl, File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent/utils.py", line 84, in get raise FakeUserAgentError('Maximum amount of retries reached') fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached 1|F8331:/ $`

can anybody help me? please?

**Comment by Martypary** [comment]
The solution ''pip install fake-useragent --upgrade'' worked for me, but this did not work for my bot with proxy. The robot with proxy does nothing.
Is it possible that this is due to a new instagram update, because my proxy has always done well.

thank you in advance,
martijn

**Comment by kddww8** [comment]
> > mine resolved with `pip install fake-useragent --upgrade`
> 
> OMG !!!!!!
> 
> You are a legend!
> It worked, thank you very much.
> 
> So after your tip I just had to do the 1509 fix and I was good to go.
> Thanks again dude you just made my day.

Worked for me too!

**Comment by volkovsurf** [comment]
> mine resolved with `pip install fake-useragent --upgrade`

when I type this in it tells me: 
Requirement already up-to-date: fake-useragent in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (0.1.11)

and if I typer python example.py it gives me the initial error of this topic, someone help please

**Comment by 5ergi0** [comment]
Guys I've tried all here with 2.7 and 3.6 python version. All the requests was already satisfied in both cases using ''pip'' and ''pip3'' and  trying to run with ''python'' and ''python3'' but it stills wrong. I don't know what else could I do...
Thanks for your time!

**Comment by ciessielski** [comment]
Try changing `fake_ua = UserAgent()` to `fake_ua = UserAgent(verify_ssl=False, use_cache_server=False)` in instabot.py

**Comment by CyrilGrd** [comment]
@ciessielski Now it works !!! thanks dude

**Comment by 5ergi0** [comment]
Jesus Christ! You are a genious @ciessielski .
Finally this is fixed but now I get [#1669](https://github.com/instabot-py/instabot.py/issues/1669). 
We'll see what happens. Thanks a lot!

**Comment by pabl0gallard0** [comment]
> UPDATE: SOLUTION FOUND!
> after trying solutions from @emgugs and @brain-wash I reinstalled all the requirements and fake_useragent by
> 
> `sudo pip install fake_useragent`
> 
> then it shows at least login instead of crash directly, however it was not possible to login and this error occurs
> 
> `Traceback (most recent call last): File "example.py", line 52, in unfollow_whitelist=['example_user_1', 'example_user_2']) File "/Users/-/Documents/instabot.py-master 8/src/instabot.py", line 234, in init self.login() File "/Users/-/Documents/instabot.py-master 8/src/instabot.py", line 303, in login self.user_id = ui.get_user_id_by_login(self.user_login) File "/Users/-/Documents/instabot.py-master 8/src/userinfo.py", line 42, in get_user_id_by_login json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}') AttributeError: 'NoneType' object has no attribute 'group'`
> 
> I fixed this error by using this method [#1509 (comment)](https://github.com/instabot-py/instabot.py/issues/1509#issuecomment-414965794)
> 
> Change src/userinfo.py line 42 to below.
> 
> `json_info = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')`
> 
> now everything runs happily on both Python2 and Python3
> 
> I know absolutly nothing about programming but solving problem feels pretty good :) Hope this will help

I did all you sayd and I still have the next issue! any help please??? 🙏🏼

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/iclons3/Desktop/bot/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/iclons3/Desktop/bot/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/iclons3/Desktop/bot/src/userinfo.py", line 43
    id_user = json_info['entry_data']['ProfilePage'][0]['graphql']['user']['id']
    ^
IndentationError: unexpected indent

**Comment by Martypary** [comment]
My problem was solved when I downgraded visualstudio code to te 26 version. Just uninstall and reinstall and repeat the instabot setub ( correct path for python, install requirements.txt, pip install fake-useragent --upgrade and redstart pc )
Don’t change the code and it wil be working again.

**Comment by flite3** [comment]
One of the things I kept noticing was this line in my errors
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>`

when I searched for this on the net, I noticed a few other python scripts that have had this problem.  Specifically for Mac os, apparently Python 2.7, 3.6, or 3.7, these versions don't install a command called certifi.  If you go into your applications folder -> python 2.7/3.6/3.7 there is a file there called Install Certificates.command.

If you run this file in terminal (open a terminal window, drag this file to the window, then hit return), this will install certifi, which will allow Fake_Useragent to verify ssl certificates, which seems to be causing this whole mess in the first place.  Well, that's what worked for me at least.  My version of instabot.py seems to be working fine now.

**Comment by huuphongnguyen** [comment]
> Try changing `fake_ua = UserAgent()` to `fake_ua = UserAgent(verify_ssl=False, use_cache_server=False)` in instabot.py

Awesome guys. Thank you

**Comment by papaloam** [comment]
> One of the things I kept noticing was this line in my errors
> `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>`
> 
> when I searched for this on the net, I noticed a few other python scripts that have had this problem. Specifically for Mac os, apparently Python 2.7, 3.6, or 3.7, these versions don't install a command called certifi. If you go into your applications folder -> python 2.7/3.6/3.7 there is a file there called Install Certificates.command.
> 
> If you run this file in terminal (open a terminal window, drag this file to the window, then hit return), this will install certifi, which will allow Fake_Useragent to verify ssl certificates, which seems to be causing this whole mess in the first place. Well, that's what worked for me at least. My version of instabot.py seems to be working fine now.

Perfect it worked for me thanks so much... Now I'm having the AttributeError

**Comment by pabl0gallard0** [comment]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/iclons3/Desktop/bot/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/iclons3/Desktop/bot/src/instabot.py", line 302, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/iclons3/Desktop/bot/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

I have this problem now! can anyone help? 🙏🏼

**Comment by Abhaya1998** [comment]
i have found that using this order of parameter doesn't works.
```ua=UserAgent(use_cache_server=False,verify_ssl=False)```

It only works when the parameters are provided like this.
```ua=ua(verify_ssl=False,use_cache_server=False)```

Not: Do run this command before-
```pip install fake-useragent --upgrade```
