### ISSUE TITLE
Unfollow not working

### ISSUE THREAD

**Issue by rworang** [instabot-py/instabot.py#2096]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (Fedora 29)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2
```

#### Pip Version?
```
pip 18.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)
```

#### Description of your issue

```
The bot does not unfollow accounts, it shows 'Trying to unfollow #1:' then goes over the other steps and as soon as it tries to unfollow it shows exactly 'Trying to unfollow #1:' again.
It has done this since I installed it a couple of days ago. I can also confirm my following amount is not decreasing.
I have tried messing with the unfollow settings but nothing changes. Current settings listed below.
```

#### Config

```
like_per_day = 147
comments_per_day = 0
max_like_for_one_tag = 25
follow_per_day = 21
follow_time = 12000
user_min_follow = 100
unfollow_per_day = 247
tag_list = [-Filled with tags I specified-]
unfollow_not_following = true
unfollow_selebgram = true
unfollow_probably_fake = true
unfollow_inactive = true
unfollow_recent_feed = true
unfollow_whitelist = [-Filled with users I specified-]
```
Is there a way to empty the unfollow timer cache or something? I have adjusted the follow_time parameter from 36000 to 12000 and before that 24000.

**Comment by malaybasu** [comment]
Can confirm that unfollow no longer works.

**Comment by adchsm** [comment]
Yep, I'm also experiencing this. Also for `unfollow_everyone`.

**Comment by mabond007** [comment]
I am still getting the issue

![image](https://user-images.githubusercontent.com/34668868/56165292-91fa0b00-5fa0-11e9-84ce-c9b894716732.png)

**Comment by vladpazych** [comment]
I created a pull request #2110 that should fix the problem.

**Comment by DailyMatters** [comment]
I've already done `python3 -m pip install instabot-py`, but it's still not working. I'm still having the 

`18.04.2019_13:00 Trying to unfollow #1:
18.04.2019_13:00 Looks like there is nobody to unfollow.`

error.

**Comment by vladpazych** [comment]
@DailyMatters Just a thought. Did you check `follow_time` option? You may have followed 100 people and they will be unfollowed when `follow_time` countdown finishes.

**Comment by dadealer** [comment]
Hi,
how can I update die instabot.py? 
I try using:

python3 -m pip install instabot-py --no-cache-dir --upgrade
&
python3 -m pip install instabot-py

but it will be the old file where the change ist not in.

**Comment by dimisdas** [comment]
This should be fixed on the latest version (--upgrade using pip). Closing the issue, feel free to comment if it persists.

**Comment by olaims** [comment]
I'm with the same issue and same config.

I also tried with "unfollow_everyone" but keep showing "looks like there is nobody to unfollow"
