### ISSUE TITLE
Commenting doesn't work anymore

### ISSUE THREAD

**Issue by hespress212** [instabot-py/instabot.py#2578]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [x] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [X ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [ ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
Python 3.8.2
#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```
Installed version 0.7.1
#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

2020-03-25 16:55:11,380 - express_family_travelers - InstaBot - DEBUG - Will not like this media: number of likes 1 does not meet media_min_like requirements
2020-03-25 16:55:11,832 - express_family_travelers - InstaBot - WARNING - Could not comment media B-KREXdAI0U, url: https://www.instagram.com/p/B-KREXdAI0U/: status code: 200. Reason:
<!DOCTYPE html>
<html lang="en" class="no-js logged-in client-root">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
Ben, Sab &amp; Antho on Instagram: “Jour 6 de #confinement volontaire au #mexique  Les mesures ne sont pas officielles ici, mais il est conseillé de #restezchezvous nous avons…”
</title>

        <meta name="robots" content="noimageindex, noarchive">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="theme-color" content="#ffffff">
        <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
        <link rel="manifest" href="/data/manifest.json">

        <link rel="preload" href="/static/bundles/metro/ConsumerUICommons.css/b9d20cb62241.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerAsyncCommons.css/3e40f00fb1b6.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/Consumer.css/4f8a21cb25e7.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/PostPageContainer.css/2eff017f1aad.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/Vendor.js/5a56d51ae30f.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/en_US.js/c66097134e1e.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerLibCommons.js/3021651d298d.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerUICommons.js/fd937ada94f0.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerAsyncCommons.js/fa823b45bb3f.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/Consumer.js/94d052b4c248.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/PostPageContainer.js/87e01c8777f1.js" as="script" type="text/javascript" crossorigin="anonymous" />

        <script type="text/javascript">
        (function() {
  var docElement = document.documentElement;
  var classRE = new RegExp('(^|\\s)no-js(\\s|$)');
  var className = docElement.className;
  docElement.className = className.replace(classRE, '$1js$2');
})();
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by hespress212** [comment]
my issue ,when i start scrpit and after 2 or 3 mns i have this issue 



2020-03-25 16:55:11,380 - XXXXXX - InstaBot - DEBUG - Will not like this media: number of likes 1 does not meet media_min_like requirements
2020-03-25 16:55:11,832 - XXXXXX - InstaBot - WARNING - Could not comment media B-KREXdAI0U, url: https://www.instagram.com/p/B-KREXdAI0U/: status code: 200. Reason:
<!DOCTYPE html>
<html lang="en" class="no-js logged-in client-root">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
Ben, Sab &amp; Antho on Instagram: “Jour 6 de #confinement volontaire au #mexique  Les mesures ne sont pas officielles ici, mais il est conseillé de #restezchezvous nous avons…”
</title>


        <meta name="robots" content="noimageindex, noarchive">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="theme-color" content="#ffffff">
        <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
        <link rel="manifest" href="/data/manifest.json">

        <link rel="preload" href="/static/bundles/metro/ConsumerUICommons.css/b9d20cb62241.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerAsyncCommons.css/3e40f00fb1b6.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/Consumer.css/4f8a21cb25e7.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/PostPageContainer.css/2eff017f1aad.css" as="style" type="text/css" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/Vendor.js/5a56d51ae30f.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/en_US.js/c66097134e1e.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerLibCommons.js/3021651d298d.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerUICommons.js/fd937ada94f0.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/ConsumerAsyncCommons.js/fa823b45bb3f.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/Consumer.js/94d052b4c248.js" as="script" type="text/javascript" crossorigin="anonymous" />
<link rel="preload" href="/static/bundles/metro/PostPageContainer.js/87e01c8777f1.js" as="script" type="text/javascript" crossorigin="anonymous" />



        <script type="text/javascript">
        (function() {
  var docElement = document.documentElement;
  var classRE = new RegExp('(^|\\s)no-js(\\s|$)');
  var className = docElement.className;
  docElement.className = className.replace(classRE, '$1js$2');
})();

**Comment by rwanch** [comment]
I have the same case happening.
Looks like for some reasons the bot is not able to comment or like some posts. It then drops you the whole HTML code of the instagram page it is trying to interact with.
It's not a big deal for me, It just waits the regular time (depending on your conf, but for me its roughly 8min) and then tries to interact with another page.
You can just keep it running

**Comment by hespress212** [comment]
@rwanch thanks fo your reply . 
can i show your configuration ?

**Comment by thecatextremist** [comment]
Add this to the config file, after max_like_for_one_tag. You can adjust this number to suit your needs.

**media_min_like: 0**

**Comment by Hokseed** [comment]
Same here... And I have the feeling that the bot is doing this error at every comment is trying to post...

**Comment by hespress212** [comment]
i tested but i have the same issue :(

**Comment by mariyagcv** [comment]
+1 same issue for each attempt it does

**Comment by LoanDEV** [comment]
> 
> 
> +1 same issue for each attempt it does

Same

**Comment by nickgryg** [comment]
Commenting issue has been fixed in version `0.7.3`.

**Comment by Hokseed** [comment]
Are you sure ? Im in 0.7.4 now, I dont have the error anymore but comments still don't work

**Comment by nickgryg** [comment]
Yes, I'm sure. It works for me.

**Comment by loan-dev** [comment]
Yeah, It works 👌 ty

**Comment by maximepeabody** [comment]
I'm also on 0.7.4, and I get: 


"2020-04-05 11:33:54,909 - INFO - Going to comment medias by discovermusic hashtag
2020-04-05 11:33:59,955 - INFO - Going to comment 100 medias.                                                                             
 12%|████████████                                                                                        | 12/100 [00:09<01:07,  1.31it/s]
Blacklist hashtag found in media, skipping!
 73%|█████████████████████████████████████████████████████████████████████████                           | 73/100 [00:56<00:20,  1.30it/s]
Blacklist hashtag found in media, skipping!
 78%|██████████████████████████████████████████████████████████████████████████████                      | 78/100 [01:00<00:17,  1.25it/s]
Blacklist hashtag found in media, skipping!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:17<00:00,  1.28it/s]
2020-04-05 11:35:17,892 - INFO - DONE: Total commented on 0 medias. "

**Comment by nickgryg** [comment]
>> Blacklist hashtag found in media, skipping!
This is the reason, doesn't it?

**Comment by maximepeabody** [comment]
> This is the reason, doesn't it?
No I don't think so, that would only account for 3 of the 100 comments. I tried it on a single one, and it looks like it's the action that's getting blocked.

**Comment by nickgryg** [comment]
1. You are not using pure `instabot-py` as I see from your output.
2. The library provides accurate reason why it's happening for first posts.
3. If commenting action is blocked by Instagram, that's not a bot issue. You are trying to comment 100 issues in two minutes. Of course, IG has banned a bot.
3. The bug which was described in this issue (please read the first post) is fixed.

That's why I'm closing this issue. Cheers.
