### ISSUE TITLE
Instabot.py multiple accounts and proxies error 400

### ISSUE THREAD

**Issue by deathmo** [instabot-py/instabot.py#783]
Hey I'm running 6 instabots via python I use different proxies for each account! When I start a new bot with new account and proxy I get the error 400 FOR ALL BOTS after the first like with the new one. What's the problem what can I do?

**Comment by deathmo** [comment]
All accounts work well on app*

**Comment by justinf102** [comment]
same :(

**Comment by zhen737** [comment]
Having the exact same issue, all assigned a private proxy per account, or even changed new proxy provider, still can't fix it.

**Comment by justinf102** [comment]
I fixed my problem. I dialed down on likes and follows. And zhen, I guess make sure your proxies are close to your location.

**Comment by wizarduk** [comment]
@deathmo are u still getting this issue ?

are you using a local ip close to you or are you using random servers ?

**Comment by Blacksmith1234** [comment]
@deathmo please help. Can u tell us how you can use the bot through proxies? I always got error messages like this #821

**Comment by HenryCooperGithub** [comment]
Problem is not related to the library . Use 1 proxy per account and / or change the user agent . **We will implement this in the future .**

**Comment by deathmo** [comment]
okay thank you. yes local and less likes fiexed it
